### PR TITLE
Auto generate access and secret keys for Minio

### PR DESCRIPTION
**Pull request by fetmar**
- Added a random alpha numeric `20` character access key when no specified value is supplied with `values.yaml`.
- Added a random alpha numeric `40` character secret key when no specified value is supplied with `values.yaml`.
- Added annotation to keep the random secrets after an upgrade.
- Added to NOTES.txt and updated previous instructions.
- Updated README.md

Tested with minikube.

```
helm install ./stable/minio --name m --namespace default
```

### CODE REVIEW

**Comment by harshavardhana** [comment]
Generating random keys might be problematic for distributed setup. So you might have to think about that ..

**Comment by harshavardhana** [comment]
Unless the generated keys are same for all the deployed instances in a distributed setup.

**Comment by fetmar** [comment]
@harshavardhana That's correct. I'll run a few tests and see if that presents any problems at any rate. 

I did find and fix another problem though. I didn't account for the config map passing the keys from `Values` to config.json. My solution was to remove them from `config.json` since they will be overridden by the environment variables.

Also, the resource-policy doesn't work the way I thought it did. It will generate a new set of keys each time the helm chart is upgraded. Do you think that presents any problems to have the keys changing each upgrade? I can make that very explicit in the documentation. You can do `helm upgrade --recreate-pods min ./stable/minio` to make sure all the pods are restarted with the correct secret keys.

**Comment by harshavardhana** [comment]
That would present problems for users since access key and secret key are remembered. A helm upgrade should not chnage the access and secret keys.

**Comment by fetmar** [comment]
How are they remembered?

**Comment by harshavardhana** [comment]
Client SDKs remember access credentials and if changing these can break apps

**Comment by fetmar** [comment]
I think for those cases, wouldn't client SDKs also follow the same 12 factor app pattern and get the credentials from an environment variable and from the secret?

**Comment by harshavardhana** [comment]
> I think for those cases, wouldn't client SDKs also follow the same 12 factor app pattern and get the credentials from an environment variable and from the secret?

You are expecting client and server are running on the same server which is hardly the case. Changing credentials on server side is a serious issue.

**Comment by fetmar** [comment]
Ah, yes. I was expecting that they were running in the same kubernetes cluster. Ok. I will close this. Thank you for taking the time.

**Pull request closed without merging**
